version: '3.9'

services:
    website:
        restart: unless-stopped
        build: .
        ports:
            - 127.0.0.1:${PORT}:8080
        extra_hosts:
            - host.docker.internal:host-gateway
