description: Developer and Hacker 💻🪲
footer: |-
  [domy;sh](mailto:me@domy.sh) -c '💻'  🐈

  `Made with ♥️ by DomySh` - [`/src `](https://github.com/domysh/domy.sh)
name: Domingo Dirutigliano
site_name: DomySh
profile_img: Laurea_photo_compressed.jpg
