description: Building and breaking systems 💻🪲
footer: |-
  [domy;sh](mailto:me@domy.sh) -c '💻'  🐈

  `Made with ♥️ by DomySh`
name: Domingo Dirutigliano
site_name: Portfolio - DomySh
profile_img: Laurea_photo_compressed.jpg
